apiVersion: ko.dev/v1beta1
kind: Config
metadata:
  name: wirety-server
build:
  # This will copy the migrations directory into /migration in the image
  # when building with ko
  # See: https://ko.build/config/
  resources:
    - type: static
      path: internal/adapters/db/postgres/migrations
      dest: /migration